config/routes.rb
Rails.application.routes.draw do
  resources :food_entries
  resources :goals
  resources :foods
  resources :foods
  resources :foods
  get 'sessions/new'
  resources :doctors
  resources :profilepics
  resources :users
  get 'azalea/index'
  get 'users/new'
  get 'doctors/new'
  get 'doctors/show'
  get 'doctors/show'
  get 'foods/show'
  get 'goals/show'
  get 'users/show'
  get 'foods/new'
  get 'users/:id/tracking' => 'users#tracking'
  get 'users/tracking/id' => 'users#tracking'
  root 'azalea#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'food_entries/create'

end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
  has_secure_password
  has_many :food_entries
  has_many :goals
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @current_user = User.find_by(id: params[:id])
    @entries = @current_user.food_entries
    @goals = @current_user.goals
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def tracking
    @current_user = User.find_by(id: params[:id])
    @today = Time.now.to_date
    @entries = @current_user.food_entries
    @foods = []
    @entries.each do |entry|
      food = Food.find_by(id: entry.food_id)
      @foods.push(food)
    end
    @entries = @current_user.food_entries
    @goals = @current_user.goals
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastName, :age, :sex, :height, :weight, :pictureName, :picture, :username, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-sm-4">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight,:class=>"form-control" %>
  </div>
  <div class="field">
    <%=f.label :picture %><br>    
    <%= f.file_field :picture, :class=>"btn verde"%>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password,:class=>"form-control"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1>Editing User</h1>

	<%= render 'form' %>
	<hr>
	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
</div>	

app/views/users/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>
  <div class="input-group"> <span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>

   <input id="filter" type="text" class="form-control" placeholder="Type here...">
   </div>
   <br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Lastname</th>
        <th>Age</th>
        <th>Sex</th>
        <th>Height</th>
        <th>Weight</th>
        <th>Picture</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="searchable">
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.lastName %></td>
          <td><%= user.age %></td>
          <td><%= user.sex %></td>
          <td><%= user.height %></td>
          <td><%= user.weight %></td>
          <td><%= image_tag(user.picture_url, :width => 80) if user.picture.present? %></td>
          <td><button type="button" class="btn verde" ><%= link_to 'Show', user %></td></button>
          <td><button type="button" class="btn btn-warning" ><%= link_to 'Edit', edit_user_path(user) %></td></button>
          <td><button type="button" class="btn btn-danger" ><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td></button>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>  
  <button type="button" class="btn verde" ><%= link_to 'New User', new_user_path %></button>
</div>  
<script>
  $(document).ready(function () {

    (function ($) {

        $('#filter').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});
</script>

app/views/users/new.html.erb
<div class="container">
<h1>New Patient</h1>
<hr>
<%= render 'form' %>
<hr>
<button type="button" class="btn verde" ><%= link_to 'Back', users_path %></button>
</div>

app/views/users/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="ih-item circle effect1 col-sm-2   "><a href="#">
        <div class="spinner"><div ><%= image_tag(@user.picture_url,:class=>"img-circle pull-left") if @user.picture.present? %></div></div>
        
        </a>
  </div>
  <br>
  <h1 class="pull-left col-sm-9">Patient Info</h1>
  <br><br><br><br><br><br><br><br><br>


  <br /> <br />
  <br />
 <div class="container">
  <p>
  <label >Name:</label>
    <%= @user.name %>
  </p>
  <hr>
  <p>
    <label>Lastname:</label>
    <%= @user.lastName %>
  </p>
  <hr>
  <p>
    <label>Age:</label>
    <%= @user.age %>
  </p>
  <hr>
  <p>
    <label>Sex:</label>
    <%= @user.sex %>
  </p>
  <hr>
  <p>
    <label>Height:</label>
    <%= @user.height %>
  </p>
  <hr>
  <p>
    <label>Weight:</label>
    <%= @user.weight %>
  </p>
  <hr>
  <p>
    <label>Username:</label>
    <%= @user.username %>
  </p>
  <hr>
 </div> 

  <hr>
</div>  

app/views/users/tracking.html.erb
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
<div class="container">
	<p id="notice"><%= notice %></p>

	<h1>Tracking</h1>
	<hr/>
</div>
<br><br>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_div"></div>
<div class="container">
<div class="col-sm-6">
<h1>My Daily Food</h1>
<div class="input-group col-sm-6"> <span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>

   <input id="filter" type="text" class="form-control" placeholder="Type here...">
</div>
   <br>

<table class="table table-striped">
  <thead >
    <tr>
      <th>Restaurant</th>
      <th>Name</th>
      <th>Calories</th>
      <th>Fat grams</th>
      <th>Sugar grams</th>
      <th>Location</th>
      <th>Picture</th>
    </tr>
  </thead>

  <tbody class="searchable">
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.rest_name %></td>
        <td><%= food.name %></td>
        <td><%= food.cal %></td>
        <td><%= food.fat %></td>
        <td><%= food.sugar %></td>
        <td><%= food.location %></td>
        <td><%= image_tag(food.picture_url, :width => 80) if food.picture.present? %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="col-sm-6">
<h1>My Goals</h1>
<% @goals.each do |goal| %>
      <%= render goal %>
      </tr>
    <% end %>
</div>
<%= link_to 'New Goal', new_goal_path, class: 'btn verde' %>
<br><br>


<div class="col-sm-12">
<p id="notice"><%= notice %></p>

<h1>Add Food</h1>
<div class="input-group"> <span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>

   <input id="filterz" type="text" class="form-control" placeholder="Type here...">
   </div>
   <br>
<table class="table table-striped">
  <thead >
    <tr>
      <th>Name</th>
      <th>Restaurant</th>
      <th>Calories</th>
      <th>Fat grams</th>
      <th>Location</th>
      <th>Picture</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="searchablez">
    <% Food.all.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.rest_name %></td>
        <td><%= food.cal %></td>
        <td><%= food.fat %></td>
        <td><%= food.location %></td>
        <td><%= image_tag(food.picture_url, :width => 80) if food.picture.present? %></td>
        <td><%= button_to 'Add',
                class: 'btn verde',
                action: 'create',
                food_id: food.id,
                controller: 'food_entries',
                :method => :post
                %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<script>
  $(document).ready(function () {

    (function ($) {

        $('#filterz').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchablez tr').hide();
            $('.searchablez tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});
</script>




<script>
  $(document).ready(function () {

    (function ($) {

        $('#filter').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});
</script>



<script>
google.charts.load('current', {packages: ['corechart', 'line']});
google.charts.setOnLoadCallback(drawBasic);

function drawBasic() {

      var data = new google.visualization.DataTable();
      data.addColumn('date', '');
      data.addColumn('number', 'Calories');

      data.addRows([
          [new Date(2016, 3, 19), 1780], [new Date(2016, 3, 20), 1920],  
          [new Date(2016, 3, 21), 2020], [new Date(2016, 3, 22), 2185],  
          [new Date(2016, 3, 23), 2000], [new Date(2016, 3, 24), 1985],  
          [new Date(2016, 3, 25), 2300],  [new Date(2016, 3, 26), 1791]
      ]);

      var options = {
        hAxis: {
          title: 'Date'
        },
        vAxis: {
          title: 'Calories'
        }
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

      chart.draw(data, options);
    }
</script>
<script>
  $(document).ready(function () {

    (function ($) {

        $('#filters').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchablexx tr').hide();
            $('.searchablexx tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});
</script>