config/routes.rb
Rails.application.routes.draw do
  resources :food_entries
  resources :goals
  resources :foods
  resources :foods
  resources :foods
  get 'sessions/new'
  resources :doctors
  resources :profilepics
  resources :users
  get 'azalea/index'
  get 'users/new'
  get 'doctors/new'
  get 'doctors/show'
  get 'doctors/show'
  get 'foods/show'
  get 'goals/show'
  get 'users/show'
  get 'foods/new'
  get 'users/:id/tracking' => 'users#tracking'
  get 'users/tracking/id' => 'users#tracking'
  root 'azalea#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'food_entries/create'

end

app/models/food.rb
class Food < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:res_Id, :cal, :fat, :sugar, :location, :picture)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="ih-item circle effect1 col-sm-2   "><a href="#">
        <div class="spinner"><div ><%= image_tag(food.picture_url,:class=>"img-circle pull-left") if food.picture.present? %></div></div>
        
        </a>
  </div>
  <br>
  <h1 class="pull-left col-sm-9">Food Info</h1>
  <br><br><br><br><br><br><br><br><br>
<div class="container">
<p>
  <strong><%= food.name %></strong>
</p>

<p>
  <strong>Restaurant</strong>
  <%= food.rest_name%>
</p>
<hr>
<p>
  <label>Cal:</label>
  <%= food.cal %>
</p>
<hr>
<p>
  <label>Fat:</label>
  <%= food.fat %>
</p>
<hr>
<p>
  <label>Sugar:</label>
  <%= food.sugar %>
</p>
<hr>
<p>
  <label>Location:</label>
  <%= food.location %>
</p>
<hr>
</div>
</div>

app/views/foods/_form.html.erb
<div class="col-sm-4">
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rest_name %><br>
    <%= f.text_field :rest_name,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :cal %><br>
    <%= f.number_field :cal,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :fat %><br>
    <%= f.number_field :fat,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :sugar %><br>
    <%= f.number_field :sugar,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>    
    <%= f.file_field :picture,:class=>"btn verde" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="container">
<h1>Editing Food</h1>

<%= render 'form' %>
<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>
</div>

app/views/foods/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>
<div class="input-group"> <span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>

   <input id="filter" type="text" class="form-control" placeholder="Type here...">
   </div>
   <br>
<table class="table table-striped">
  <thead >
    <tr>
      <th>Name</th>
      <th>Restaurant</th>
      <th>Calories</th>
      <th>Fat grams</th>
      <th>Location</th>
      <th>Picture</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="searchable">
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.rest_name %></td>
        <td><%= food.cal %></td>
        <td><%= food.fat %></td>
        <td><%= food.sugar %></td>
        <td><%= food.location %></td>
        <td><%= image_tag(food.picture_url, :width => 80) if food.picture.present? %></td>
        <td><button type="button" class="btn verde" ><%= link_to 'Show', food %></td></button>
        <td><button type="button" class="btn btn-warning" ><%= link_to 'Edit', edit_food_path(food) %></td></button>
        <td><button type="button" class="btn btn-danger" ><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td></button>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn verde" ><%= link_to 'New Food', new_food_path %></button>
<script>
  $(document).ready(function () {

    (function ($) {

        $('#filter').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});
</script>

app/views/foods/new.html.erb
<div class="container">
<h1>New Food</h1>
<hr>
<%= render 'form' %>

<hr>
<button type="button" class="btn verde" ><%= link_to 'Back', foods_path %></button>
</div>

app/views/foods/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="ih-item circle effect1 col-sm-2   "><a href="#">
        <div class="spinner"><div ><%= image_tag(@food.picture_url,:class=>"img-circle pull-left") if @food.picture.present? %></div></div>
        
        </a>
  </div>
  <br>
  <h1 class="pull-left col-sm-9">Food Info</h1>
  <br><br><br><br><br><br><br><br><br>
<div class="container">
<p>
  <strong><%= @food.name %></strong>
</p>

<p>
  <strong>Restaurant</strong>
  <%= @food.rest_name%>
</p>
<hr>
<p>
  <label>Cal:</label>
  <%= @food.cal %>
</p>
<hr>
<p>
  <label>Fat:</label>
  <%= @food.fat %>
</p>
<hr>
<p>
  <label>Sugar:</label>
  <%= @food.sugar %>
</p>
<hr>
<p>
  <label>Location:</label>
  <%= @food.location %>
</p>
<hr>
</div>
<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>
</div>