config/routes.rb
Rails.application.routes.draw do
  resources :food_entries
  resources :goals
  resources :foods
  resources :foods
  resources :foods
  get 'sessions/new'
  resources :doctors
  resources :profilepics
  resources :users
  get 'azalea/index'
  get 'users/new'
  get 'doctors/new'
  get 'doctors/show'
  get 'doctors/show'
  get 'foods/show'
  get 'goals/show'
  get 'users/show'
  get 'foods/new'
  get 'users/:id/tracking' => 'users#tracking'
  get 'users/tracking/id' => 'users#tracking'
  root 'azalea#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'food_entries/create'

end

app/models/food_entry.rb
class FoodEntry < ActiveRecord::Base
  belongs_to :user
  has_one :food
end

app/controllers/food_entries_controller.rb
class FoodEntriesController < ApplicationController
  before_action :set_food_entry, only: [:show, :edit, :update, :destroy]

  # GET /food_entries
  # GET /food_entries.json
  def index
    @food_entries = FoodEntry.all
  end

  # GET /food_entries/1
  # GET /food_entries/1.json
  def show
  end

  # GET /food_entries/new
  def new
    @food_entry = FoodEntry.new
    @foods = FoodEntry.find(params[:id])
  end

  # GET /food_entries/1/edit
  def edit
  end

  # POST /food_entries
  # POST /food_entries.json
  def create
#    @food_entry = FoodEntry.new(food_entry_params)
    @user = User.find_by(id: session[:user_id])
    @entry = @user.food_entries.create(user_id: @user.id,
                                       food_id: params[:food_id],
                                       date: Time.now)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to :back, notice: 'Food entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_entries/1
  # PATCH/PUT /food_entries/1.json
  def update
    respond_to do |format|
      if @food_entry.update(food_entry_params)
        format.html { redirect_to @food_entry, notice: 'Food entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_entry }
      else
        format.html { render :edit }
        format.json { render json: @food_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_entries/1
  # DELETE /food_entries/1.json
  def destroy
    @food_entry.destroy
    respond_to do |format|
      format.html { redirect_to food_entries_url, notice: 'Food entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_entry
      @food_entry = FoodEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_entry_params
      params.fetch(:food_entry, {})
    end
end

app/helpers/food_entries_helper.rb
module FoodEntriesHelper
end

app/views/food_entries/_food_entry.html.erb
<div>
  <b> <%= food_entry.food_id %> </b> <br />
  <b> <%= food_entry.user_id %> </b> <br />
  <b> <%= food_entry.date %> </b> <br />
</div>

app/views/food_entries/_form.html.erb
<%= form_for(FoodEntry.new) do |f| %>
  
<% end %>
<div class="container">
<p id="notice"><%= notice %></p>
<div class="input-group"> <span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>

   <input id="filter" type="text" class="form-control" placeholder="Type here...">
   </div>
   <br>
<table class="table table-striped">
  <thead >
    <tr>
      <th>Restaurant</th>
      <th>Name</th>
      <th>Calories</th>
      <th>Fat grams</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="searchable">
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.rest_name %></td>
        <td><%= food.name %></td>
        <td><%= food.cal %></td>
        <td><%= food.fat %></td>
        <td><%= food.sugar %></td>
        <td><%= image_tag(food.picture_url, :width => 80) if food.picture.present? %></td>
        <td><%= button_to 'Add',
                class: 'btn verde',
                action: 'create',
                food_id: food.id,
                controller: 'food_entries',
                :method => :post
                %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<script>
  $(document).ready(function () {

    (function ($) {

        $('#filter').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchablez tr').hide();
            $('.searchablez tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});
</script>

<script>
$('#menuChick').show(function(){
    $(#'tableChick').toggle();
});

</script>

app/views/food_entries/edit.html.erb
<h1>Editing Food Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_entry %> |
<%= link_to 'Back', food_entries_path %>

app/views/food_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Food Entries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_entries.each do |food_entry| %>
      <tr>
        <td>Food ID: <%= food_entry.food_id %></td>
        <td>User ID: <%= food_entry.user_id %></td>
        <td><%= link_to 'Show', food_entry %></td>
        <td><%= link_to 'Edit', edit_food_entry_path(food_entry) %></td>
        <td><%= link_to 'Destroy', food_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food entry', new_food_entry_path %>

app/views/food_entries/new.html.erb
<div class="container">
<h1>New Food Entry</h1>

<%= render 'form' %>

</div>

app/views/food_entries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_food_entry_path(@food_entry) %> |
<%= link_to 'Back', food_entries_path %>