config/routes.rb
Rails.application.routes.draw do
  resources :food_entries
  resources :goals
  resources :foods
  resources :foods
  resources :foods
  get 'sessions/new'
  resources :doctors
  resources :profilepics
  resources :users
  get 'azalea/index'
  get 'users/new'
  get 'doctors/new'
  get 'doctors/show'
  get 'doctors/show'
  get 'foods/show'
  get 'goals/show'
  get 'users/show'
  get 'foods/new'
  get 'users/:id/tracking' => 'users#tracking'
  get 'users/tracking/id' => 'users#tracking'
  root 'azalea#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'food_entries/create'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @user = User.find_by(session[:user_id])

    @goal = @user.goals.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:type_id, :title, :end, :date, :user_id, :quantity)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<div class="col-sm-6">
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.number_field :end,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date,:class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity,:class=>"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div class="container">
<br />
<strong><p>
  To accomplish <%= goal.title %>,
   you will need to 
  <% if goal.type_id == 1 %>
    lose <%= goal.quantity %>
    pounds
  <% elsif goal.type_id == 2 %>
    gain <%= goal.quantity %>
    pounds
  <% elsif goal.type_id == 3 %>
    eat <%= goal.quantity %>
    calories
  <% else %>
    burn <%= goal.quantiy %>
    calories
  <% end %>

  <% if goal.end == 1 %>
    daily.
  <% elsif goal.end == 2 %>
    weekly.
  <% elsif goal.end == 3 %>
    monthly.
  <% else %>
    by <% goal.date %>
  <% end %>
</p></strong>
</div>
<hr>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>My Goals</h1>
<div class="input-group"> <span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>

   <input id="filter" type="text" class="form-control" placeholder="Type here...">
   </div>
   <br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Type</th>
      <th>Title</th>
      <th>End</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="searchable">
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.type_id %></td>
        <td><%= goal.title %></td>
        <td><%= goal.end %></td>
        <td><%= goal.date %></td>
        <td><button type="button" class="btn verde" ><%= link_to 'Show', goal %></td></button>
        <td><button type="button" class="btn btn-warning" ><%= link_to 'Edit', edit_goal_path(goal) %></td></button>
        <td><button type="button" class="btn btn-danger" ><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td></button>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn verde" ><%= link_to 'New Goal', new_goal_path %></button>
<script>
  $(document).ready(function () {

    (function ($) {

        $('#filter').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});
</script>

app/views/goals/new.html.erb
<div class="container">
<h1>New Goal</h1>
<hr>
<%= render 'form' %>
<hr>
<button type="button" class="btn verde" ><%= link_to 'Back', goals_path %></button>
</div>

app/views/goals/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<br>
  <h1 class="col-sm-9">Patient Goals</h1>
<div class="container">
  <br><br><br><br>
<div class="container">
<p>
  <label>Type:</label>
  <%= @goal.type_id %>
</p>
<hr>
<p>
  <label>Title:</label>
  <%= @goal.title %>
</p>
<hr>
<p>
  <label>End:</label>
  <%= @goal.end %>
</p>
<hr>
<p>
  <label>Date:</label>
  <%= @goal.date %>
</p>
<hr>
<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>
<hr>
  </div>
</div>